FROM ruby:3.1.2-alpine

RUN apk add --no-cache \
  build-base \
  linux-headers \
  cmake \
  pkgconfig \
  mariadb-dev \
  tzdata \
  nodejs \
  shared-mime-info \
  yaml-dev \
  git \
  curl \
  bash \
  gcompat \
  libxml2-dev \
  libxslt-dev

# Alpine 3.16 has no mecab package. Compile the small 0.996 library only (no ipadic).
RUN curl -fsSL http://deb.debian.org/debian/pool/main/m/mecab/mecab_0.996.orig.tar.gz -o /tmp/mecab.tar.gz \
  && tar xzf /tmp/mecab.tar.gz -C /tmp \
  && cd /tmp/mecab-0.996 \
  && curl -fsSL -o config.guess https://raw.githubusercontent.com/gcc-mirror/gcc/master/config.guess \
  && curl -fsSL -o config.sub https://raw.githubusercontent.com/gcc-mirror/gcc/master/config.sub \
  && chmod +x config.guess config.sub \
  && ./configure --enable-utf8-only --prefix=/usr \
  && make -j"$(getconf _NPROCESSORS_ONLN)" \
  && make install \
  && rm -rf /tmp/mecab*

ENV MECABRC=/usr/etc/mecabrc
ENV BUNDLE_PATH=/myapp/tmp/docker-bundle
ENV TMPDIR=/myapp/tmp/docker-tmp

WORKDIR /myapp

EXPOSE 3000
