default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("RAILS_DATABASE_USERNAME") { "root" } %>
  password: <%= ENV.fetch("RAILS_DATABASE_PASSWORD") { "" } %>
  host: <%= ENV.fetch("RAILS_DATABASE_HOST") { "127.0.0.1" } %>

development:
  <<: *default
  database: <%= ENV.fetch("RAILS_DATABASE") { "instagram_chatbot" } %>

test:
  <<: *default
  database: <%= ENV.fetch("RAILS_DATABASE") { "instagram_chatbot_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("RAILS_DATABASE") { "instagram_chatbot_production" } %>
