api:
  time_reset_token: 2
  time_refresh_token: 30
  company: rikai
  client_name: chatbot
  shorten_url: <%= "#{ENV.fetch("CHATBOT_DOMAIN")}/s/" %>
webhook:
  verify_token: "<%= ENV.fetch("WEBHOOK_VERIFY_TOKEN") %>"
  page_facebook_access_token: "<%= ENV.fetch("PAGE_FACEBOOK_ACCESS_TOKEN") %>"
  page_instagram_access_token: "<%= ENV.fetch("PAGE_INSTAGRAM_ACCESS_TOKEN") %>"
facebook:
  sdk:
    url: https://graph.facebook.com/
    version: v14.0
  meta_app:
    app_id: "<%= ENV.fetch("FACEBOOK_APP_ID") %>"
    app_secret: "<%= ENV.fetch("FACEBOOK_APP_SECRET") %>"
aws:
  s3:
    AWS_ACCESS_KEY_ID: "<%= ENV.fetch("AWS_ACCESS_KEY_ID") %>"
    AWS_SECRET_ACCESS_KEY: "<%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>"
    S3_BUCKET: "<%= ENV.fetch("S3_BUCKET") %>"
    AWS_REGION: "<%= ENV.fetch("AWS_REGION") %>"
two_captcha:
  api_key: "<%= ENV.fetch("TWO_CAPTCHA_API_KEY") %>"
captcha:
  client_key: "<%= ENV.fetch("CAPTCHA_CLIENT_KEY") %>"
sms:
  MT_API_ENDPOINT: https://sms-api.aossms.com/p5/api/mt.json
  SMS_CODE: <%= ENV.fetch("SMS_CODE") %>
  CLIENT_ID: <%= ENV.fetch("SMS_CLIENT_ID") %>
  TOKEN: "<%= ENV.fetch("SMS_TOKEN") %>"
GMAIL_USERNAME: "<%= ENV.fetch("GMAIL_USERNAME") %>"
GMAIL_PASSWORD: "<%= ENV.fetch("GMAIL_PASSWORD") %>"
