api:
  time_reset_token: 2
  time_refresh_token: 30
  company: rikai
  client_name: chatbot
webhook:
  verify_token: 937227c494272127b7ddfdbe7ed6e723a792f0aae8f48d80f26f7d27e61d6da7a1fb71ef9e99706d279f9ca6582ad73db15d4196e4a385d272c464ca07283add
  page_facebook_access_token: EAAYoYLoNogABAE5XZAPLR1mZAoUBMZAdv9ZAKKS5wOpUhV4JCZANbO8H1PXcOjVAXmHatx7UFWoPhVlVDe62XZCJwEbJDwJWmOa9QcZCu5vTvKe95A5KKIJHhQiHgACxer9cfZAmzMvA4fGMmhpZBOrZBi1Hbfz4TUUH0ImAHBy1ed06jealJOCrIRxQmFyRQ939AZD
  page_instagram_access_token: EAAYoYLoNogABAI9hdCOyoYQxwQYcfsBWcBU6UMPsqJxKVsMZBZCUkOijZCDoT0BoaYPZCUZB1ZAe2r6tPZBTIvnOFHbPcAJHMZA6Tjng7HquoWMRvGVHoncJdqlXEo9eZArtKArnwB96kDvJQsut4f7gWtzlvv7E9FGDmZAUp7vH7pewdVIVEHSH85uJlwZCLJm2gwZD
